name: medium
type: ddit
hidden_size: 1024
cond_dim: 128
length: 1024
n_blocks: 24
n_heads: 16
scale_by_sigma: True
dropout: 0.1
caption_encoder:
  name: ${tokenizer.caption}
  pool: cls
  dropout: 0.1
  freeze: True
