defaults:
  - _self_
  - model: small-raw
  - data: default
  - worker: gpuserver
  - override hydra/launcher: submitit_slurm

tokenizer:
  text: gpt2
  caption: bert-base-uncased

tokens: 50257

training:
  n_iters: 1300001
  snapshot_freq: 50000
  log_freq: 50
  eval_freq: 100 # 100
  snapshot_freq_for_preemption: 10000
  weight: standard
  snapshot_sampling: True
  ema: 0.9999
  p_uncond: 0.1
  alpha_align: 0.1
  tau: 0.1
  eos_penalty: 0.1

graph:
  type: absorb
  file: data
  report_all: False

noise:
  type: loglinear
  sigma_min: 1e-4
  sigma_max: 20

sampling:
  predictor: euler
  steps: 128
  noise_removal: True

eval:
  perplexity: True

optim:
  weight_decay: 0
  optimizer: AdamW
  lr: 3e-4
  beta1: 0.9
  beta2: 0.999
  eps: 1e-8
  warmup: 2500
  grad_clip: 1.


hydra:
  run:
    dir: exp_local/${data.trainset.name}/${now:%Y.%m.%d}/${now:%H%M%S}
    # dir: exp_local/phish-email/2025.12.19/162857
  sweep:
    dir: exp/${data.trainset.name}/${now:%Y.%m.%d}/${now:%H%M%S}
    subdir: ${hydra.job.num}


